'use client';

import {useCallback, useEffect, useRef, useState, type FormEvent, type ReactNode} from 'react';
import {ArrowDownLeft, ArrowRight, ArrowUpRight, BadgeCheck, Boxes, Building2, Check, CheckCheck, ChevronRight, CircleHelp, ClipboardList, Factory, FileText, Landmark, LayoutDashboard, Link2, LoaderCircle, Menu, Moon, Package, Plus, RefreshCw, Search, Settings2, ShieldCheck, ShoppingCart, Sparkles, Sun, Truck, Users, Wallet, X} from 'lucide-react';
import {CubeIcon, CurrencyCircleDollarIcon, FactoryIcon, ShoppingCartIcon, TruckIcon} from '@phosphor-icons/react';
import Decimal from 'decimal.js';
import {Button} from '@/components/ui/button';
import {money, sumAmounts} from '@/lib/amount';
import {explorer, shortAddress} from '@/lib/config';
import type {Contact, Employee, ERPState, Product} from '@/lib/erp-types';

type Module = 'overview' | 'contacts' | 'sales' | 'purchasing' | 'stock' | 'production' | 'team' | 'accounting' | 'settings';
type FormKind = 'contact' | 'product' | 'sales' | 'purchase' | 'employee' | 'production';
const nav = [
  {id:'overview',label:'Genel bakış',icon:LayoutDashboard},
  {id:'contacts',label:'Müşteri & tedarikçi',icon:Users},
  {id:'sales',label:'Satış yönetimi',icon:ShoppingCart},
  {id:'purchasing',label:'Satın alma',icon:Truck},
  {id:'stock',label:'Stok & depo',icon:Boxes},
  {id:'production',label:'Üretim',icon:Factory},
  {id:'team',label:'İnsan kaynakları',icon:Building2},
  {id:'accounting',label:'Muhasebe & finans',icon:Landmark},
  {id:'settings',label:'Şirket profili',icon:Settings2},
] as const;
const titles: Record<Module,string> = {overview:'Operasyon merkezi',contacts:'İlişkilerin, bir arada',sales:'Siparişten tahsilata',purchasing:'Tedarikten ödemeye',stock:'Stoktan sevkiyata',production:'Üretimin, kontrol altında',team:'Ekibin ve ödeme planı',accounting:'Her kayıt birbirine bağlı',settings:'Şirketinin çalışma alanı'};
const subtitles: Record<Module,string> = {overview:'Bugünün açık işlerini, stok risklerini ve ödeme durumunu tek çalışma ekranından yönet.',contacts:'Müşteri ve tedarikçi bilgilerini siparişlerine ve Stellar ödemelerine bağla.',sales:'Ürün kalemlerinden sipariş oluştur, faturala, sevk et ve tahsilatı izle.',purchasing:'Mal kabulü stoğu artırır ve aynı kayıttan tedarikçi borcu oluşturur.',stock:'Depodaki her giriş, üretim tüketimi ve sevkiyatın bir kaynağı var.',production:'İş emrindeki girdileri tüket, ürettiğin ürünleri stoğa ekle.',team:'Çalışan kayıtlarından dönemlik USDC ödeme yükümlülükleri oluştur.',accounting:'Operasyon kayıtları ile doğrulanmış Stellar işlemleri aynı defterde.',settings:'İşletme bilgilerini ve finans için kullanacağın Stellar cüzdanını yönet.'};
const labels: Record<string,string> = {open:'Bekliyor',invoiced:'Faturalandı',settled:'Tahsil edildi',refunded:'İade edildi',cancelled:'İptal',ordered:'Sipariş verildi',received:'Teslim alındı',planned:'Planlandı',completed:'Tamamlandı',paid:'Ödendi'};
const formatDate = (value:number) => new Date(value).toLocaleDateString('tr-TR',{day:'2-digit',month:'short'});
const month = new Date().toISOString().slice(0,7);
function Pill({value}:{value:string}) {return <span className={'status erp-status-'+value}><i/>{labels[value] || value}</span>;}
function Metric({name,value,sub,icon}:{name:string;value:string;sub:string;icon:ReactNode}) {return <section className="stat-card"><div className="stat-heading"><span>{name}</span><span className="stat-icon">{icon}</span></div><strong>{value}</strong><p>{sub}</p><div className="stat-footer"><span className="tiny-dot"/>ERP kayıtlarından hesaplanır</div></section>;}
function Empty({title,text,icon,action,onClick}:{title:string;text:string;icon:ReactNode;action?:string;onClick?:()=>void}) {return <div className="empty-state"><div className="empty-icon">{icon}</div><h3>{title}</h3><p>{text}</p>{action && <Button variant="secondary" size="sm" onClick={onClick}><Plus size={14}/>{action}</Button>}</div>;}
function FormDialog({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}) {
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{ref.current?.showModal();},[]);
  return <dialog ref={ref} className="modal modal-wide" onCancel={onClose} onClick={e=>{if(e.target===ref.current) onClose();}}><div className="modal-header"><div><p className="eyebrow">ERP · YENİ İŞ KAYDI</p><h2>{title}</h2></div><Button size="icon" variant="ghost" aria-label="Kapat" onClick={onClose}><X size={19}/></Button></div>{children}</dialog>;
}
const formTitles:Record<FormKind,string> = {contact:'İş ortağı kaydı',product:'Ürün ve açılış stoku',sales:'Yeni satış siparişi',purchase:'Yeni satın alma siparişi',employee:'Çalışan kaydı',production:'Yeni üretim iş emri'};

export default function ERPApp(){
  const [module,setModule]=useState<Module>('overview');
  const [state,setState]=useState<ERPState|null>(null);
  const [busy,setBusy]=useState('');
  const [notice,setNotice]=useState<{text:string;error?:boolean}|null>(null);
  const [form,setForm]=useState<{kind:FormKind;id?:string}|null>(null);
  const [dark,setDark]=useState(false);
  const [mobile,setMobile]=useState(false);
  const [search,setSearch]=useState('');
  const [period,setPeriod]=useState(month);
  const load=useCallback(async()=>{const r=await fetch('/api/erp',{cache:'no-store'});const body=await r.json();if(!r.ok) throw new Error(body.error);setState(body);},[]);
  useEffect(()=>{load().catch(error=>setNotice({text:error.message,error:true}));const params=new URLSearchParams(window.location.search);const value=params.get('module');if(nav.some(n=>n.id===value))setModule(value as Module);const theme=localStorage.getItem('bridge_theme')==='dark';setDark(theme);document.documentElement.dataset.theme=theme?'dark':'light';},[load]);
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(null),8000);return()=>clearTimeout(timer);},[notice]);
  async function mutate(action:string,params:Record<string,unknown>={}){
    if(busy)return;
    setBusy(action);
    try {const r=await fetch('/api/erp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...params})});const body=await r.json();if(!r.ok)throw new Error(body.error);setState(body.state);setForm(null);setNotice({text:action==='sample'?'Örnek operasyon kayıtları eklendi. Stellar ödeme veya tahsilat verisi üretilmedi.':'İş kaydı güncellendi; bağlı modüller aynı veriyi kullanıyor.'});}catch(error){setNotice({text:error instanceof Error?error.message:'Kayıt tamamlanamadı.',error:true});}finally{setBusy('');}
  }
  function select(value:Module){setModule(value);setMobile(false);setSearch('');window.history.replaceState(null,'','/?module='+value);}
  function theme(){const value=!dark;setDark(value);document.documentElement.dataset.theme=value?'dark':'light';localStorage.setItem('bridge_theme',value?'dark':'light');}
  const company=state?.company;
  const lowStock=state?.products.filter(p=>p.quantity<=p.reorderPoint)||[];
  const payables=state?.payables.filter(p=>p.status==='open')||[];
  const saleTotal=sumAmounts(state?.sales.filter(s=>!['cancelled','refunded'].includes(s.status)).map(s=>s.total)||[]);
  const receipts=sumAmounts(state?.journal.filter(j=>j.debit==='USDC cüzdanı' && j.label.includes('Stellar tahsilatı')).map(j=>j.amount)||[]);
  const waitingProduction=state?.production.filter(j=>j.status==='planned')||[];
  const customers=state?.contacts.filter(c=>c.type==='customer')||[];
  const vendors=state?.contacts.filter(c=>c.type==='vendor')||[];
  const emptyWorkspace=state && !state.contacts.length && !state.products.length && !state.employees.length;
  const actions:Partial<Record<Module,{kind:FormKind;name:string}>>={contacts:{kind:'contact',name:'İş ortağı ekle'},sales:{kind:'sales',name:'Satış siparişi'},purchasing:{kind:'purchase',name:'Satın alma siparişi'},stock:{kind:'product',name:'Ürün ekle'},production:{kind:'production',name:'İş emri oluştur'},team:{kind:'employee',name:'Çalışan ekle'}};
  const selectedAction=actions[module];
  const contactName=(id:string)=>state?.contacts.find(c=>c.id===id)?.name||'İş ortağı';
  return <div className="app-shell erp-shell">
    <a className="skip-link" href="#erp-main">Ana içeriğe geç</a>
    {mobile && <div className="nav-scrim" onClick={()=>setMobile(false)}/>}
    <aside id="erp-navigation" className={'sidebar '+(mobile?'sidebar-open':'')}><a className="brand" href="/" aria-label="Centerp ana sayfa"><div className="brand-mark"><Link2 size={24}/></div><span>center<span className="brand-light">p</span><small>Kurumsal kaynak planlama</small></span></a><div className="workspace"><div className="workspace-avatar">CP</div><div><strong>{company?.name||'ERP workspace'}</strong><span>Şirket çalışma alanı</span></div><Building2 size={15}/></div><p className="nav-heading">İşletme</p><nav aria-label="ERP modülleri">{nav.map(n=><button key={n.id} className={'nav-link '+(module===n.id?'active':'')} onClick={()=>select(n.id)}><n.icon size={18}/><span>{n.label}</span>{n.id==='sales'&&<b>{state?.sales.length||0}</b>}</button>)}</nav><div className="erp-sidebar-finance"><p className="nav-heading">Stellar</p><a className="nav-link finance-nav" href="/finance"><ShieldCheck size={18}/><span>Ödemeler & mutabakat</span><ArrowUpRight size={14}/></a></div><div className="sidebar-bottom erp-sidebar-bottom"><div className="sidebar-footer"><span className="network-dot"/>Testnet çalışma alanı<span>Centerp v0.2</span></div></div></aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb"><Button size="icon" variant="ghost" className="mobile-menu" aria-label="Menüyü aç" aria-expanded={mobile} aria-controls="erp-navigation" onClick={()=>setMobile(true)}><Menu size={20}/></Button><span>Centerp</span><ChevronRight size={14}/><strong>{nav.find(n=>n.id===module)?.label}</strong></div><div className="topbar-actions"><span className="testnet-chip"><i/>TESTNET</span><Button variant="ghost" size="icon" aria-label={dark?'Açık tema':'Koyu tema'} onClick={theme}>{dark?<Sun size={18}/>:<Moon size={18}/>}</Button><Button asChild variant="secondary"><a href="/finance"><Wallet size={16}/>{state?.connectedAccount?shortAddress(state.connectedAccount):'Stellar finansı aç'}</a></Button></div></header>
      <main id="erp-main" tabIndex={-1}><div className={'page-heading '+(module==='overview'?'page-heading-compact':'')}><div><h1>{titles[module]}</h1><p>{subtitles[module]}</p></div><div className="heading-actions"><Button size="icon" variant="secondary" aria-label="Kayıtları yenile" disabled={!!busy} onClick={()=>load().catch(error=>setNotice({text:error.message,error:true}))}><RefreshCw size={17}/></Button>{selectedAction && <Button disabled={!state||!!busy} onClick={()=>setForm({kind:selectedAction.kind})}><Plus size={17}/>{selectedAction.name}</Button>}{module==='overview'&&<Button disabled={!state} onClick={()=>setForm({kind:'sales'})}><Plus size={17}/>Satış siparişi</Button>}</div></div>
      {busy&&<div className="busy-banner" role="status"><LoaderCircle size={16} className="spin"/>İş kayıtları ve modüller güncelleniyor.</div>}
      {!state&&<div className="erp-loading"><LoaderCircle size={25} className="spin"/><p>Şirket çalışma alanı açılıyor…</p><Button variant="secondary" onClick={()=>load().catch(error=>setNotice({text:error.message,error:true}))}>Yeniden dene</Button></div>}
      {state&&<>
      {company?.demo && <div className="erp-demo-banner"><Sparkles size={14}/><span>Örnek operasyon çalışma alanı · Örnek kayıtlar gerçek şirket veya ödeme verisi değildir.</span></div>}
      {module==='overview'&&<>
        <div className="ops-summary-line">
          <div><span>Açık satış</span><strong>{state.sales.filter(s=>['open','invoiced'].includes(s.status)).length}</strong></div>
          <div><span>Ödenecek</span><strong>{money(sumAmounts(payables.map(p=>p.amount)))}</strong></div>
          <div><span>Kritik stok</span><strong>{lowStock.length}</strong></div>
          <div><span>Testnet tahsilatı</span><strong>{money(receipts)}</strong></div>
        </div>
        <div className="ops-command-grid">
          <section className="ops-queue">
            <div className="ops-section-heading"><div><h2>İş kuyruğu</h2><p>Bugün müdahale gerektiren kayıtlar.</p></div><span>{state.sales.length+payables.length+waitingProduction.length+lowStock.length} kayıt</span></div>
            <button className="ops-queue-row" onClick={()=>select('sales')}><span className="ops-row-icon"><ShoppingCartIcon size={29} weight="duotone" aria-hidden="true"/></span><span><strong>Satış ve sevkiyat</strong><small>{state.sales.filter(s=>!s.delivered&&!['cancelled','refunded'].includes(s.status)).length} sipariş sevkiyat bekliyor</small></span><b>{money(saleTotal)}</b></button>
            <button className="ops-queue-row" onClick={()=>select('purchasing')}><span className="ops-row-icon"><TruckIcon size={29} weight="duotone" aria-hidden="true"/></span><span><strong>Tedarik ve borçlar</strong><small>{state.purchases.filter(p=>p.status==='ordered').length} mal kabulü, {payables.length} açık ödeme</small></span><b>{money(sumAmounts(payables.map(p=>p.amount)))}</b></button>
            <button className="ops-queue-row" onClick={()=>select('production')}><span className="ops-row-icon"><FactoryIcon size={29} weight="duotone" aria-hidden="true"/></span><span><strong>Üretim planı</strong><small>{waitingProduction.length} iş emri üretime alınmayı bekliyor</small></span><b>{waitingProduction.length}</b></button>
            <button className="ops-queue-row" onClick={()=>select('stock')}><span className="ops-row-icon"><CubeIcon size={29} weight="duotone" aria-hidden="true"/></span><span><strong>Stok kontrolü</strong><small>{lowStock.length} ürün yeniden sipariş seviyesinde</small></span><b>{state.products.length} kalem</b></button>
          </section>
          <aside className="ops-treasury">
            <div className="ops-treasury-head"><span>Stellar mutabakatı</span><CurrencyCircleDollarIcon size={25} weight="duotone" aria-hidden="true"/></div>
            <p>Doğrulanmış tahsilat</p><strong className="ops-treasury-amount">{money(receipts)}</strong>
            <dl><div><dt>Şirket cüzdanı</dt><dd>{company?.wallet?shortAddress(company.wallet):'Bağlı değil'}</dd></div><div><dt>Açık ödeme yükü</dt><dd>{money(sumAmounts(payables.map(p=>p.amount)))}</dd></div><div><dt>Ağ</dt><dd><i/>Testnet</dd></div></dl>
            <Button asChild><a href="/finance">Finans işlemlerini aç</a></Button>
          </aside>
        </div>
        <section className="ops-board">
          <div className="ops-section-heading"><div><h2>Operasyon hattı</h2><p>Satın almadan tahsilata kadar aynı kayıt zinciri.</p></div><button className="text-button" onClick={()=>select('accounting')}>Muhasebe defteri</button></div>
          <div className="ops-board-track">
            <button onClick={()=>select('purchasing')}><span>Satın alma</span><strong>{state.purchases.filter(p=>p.status==='ordered').length}</strong><small>mal kabulü bekliyor</small></button>
            <button onClick={()=>select('production')}><span>Üretim</span><strong>{waitingProduction.length}</strong><small>planlanan iş emri</small></button>
            <button onClick={()=>select('sales')}><span>Satış</span><strong>{state.sales.filter(s=>['open','invoiced'].includes(s.status)).length}</strong><small>açık sipariş</small></button>
            <a href="/finance"><span>Tahsilat</span><strong>{money(receipts).replace(' USDC','')}</strong><small>USDC doğrulandı</small></a>
          </div>
        </section>
        <section className="ops-ledger">
          <div className="ops-section-heading"><div><h2>Son satış kayıtları</h2><p>Sipariş, sevkiyat ve tahsilat durumu.</p></div><button className="text-button" onClick={()=>select('sales')}>Tüm satışlar</button></div>
          {state.sales.length?<div className="table-scroll"><table><thead><tr><th>Sipariş</th><th>Müşteri</th><th>Tutar</th><th>Durum</th></tr></thead><tbody>{state.sales.slice(0,5).map(s=><tr key={s.id}><td><strong>{s.code}</strong><small>{formatDate(s.createdAt)}</small></td><td>{contactName(s.contactId)}</td><td className="amount-cell">{money(s.total)}</td><td><Pill value={s.status}/></td></tr>)}</tbody></table></div>:<Empty icon={<ClipboardList size={28}/>} title="İlk satış kaydını oluştur." text="Müşteriyi ve ürünleri seç; siparişi aynı kayıttan faturaya bağla." action="Satış siparişi oluştur" onClick={()=>setForm({kind:'sales'})}/>}
        </section>
        {emptyWorkspace&&<section className="erp-sample-banner"><div><Sparkles size={19}/><div><strong>Örnek işletme kayıtlarını yükle</strong><p>Müşteri, tedarikçi, ürün ve çalışan örnekleri eklenir. Ödeme verisi eklenmez.</p></div></div><Button variant="secondary" size="sm" disabled={!!busy} onClick={()=>mutate('sample')}>Örnek veriyi yükle</Button></section>}
      </>}
      {module==='contacts'&&<section className="panel"><div className="list-toolbar"><div className="erp-list-caption"><h2>İş ortakları <span className="count-badge">{state.contacts.length}</span></h2><p>{customers.length} müşteri · {vendors.length} tedarikçi</p></div><label className="search-field"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ad veya e-posta ara" aria-label="İş ortağı ara"/></label></div>{state.contacts.length?<div className="table-scroll"><table><thead><tr><th>İŞ ORTAĞI</th><th>TÜR</th><th>İLETİŞİM</th><th>STELLAR CÜZDANI</th><th/></tr></thead><tbody>{state.contacts.filter(c=>(c.name+' '+c.email).toLocaleLowerCase('tr').includes(search.toLocaleLowerCase('tr'))).map(c=><tr key={c.id}><td><strong>{c.name}</strong></td><td><span className="pill">{c.type==='customer'?'Müşteri':'Tedarikçi'}</span></td><td>{c.email||'—'}</td><td><code>{c.wallet?shortAddress(c.wallet):'Henüz eklenmedi'}</code></td><td><Button variant="secondary" size="sm" onClick={()=>setForm({kind:'contact',id:c.id})}>Düzenle</Button></td></tr>)}</tbody></table></div>:<Empty title="Müşteri ve tedarikçini ekle." text="Tek iş ortağı kaydı siparişlerde, faturalarda ve Stellar ödemelerinde kullanılır." icon={<Users size={28}/>} action="İş ortağı ekle" onClick={()=>setForm({kind:'contact'})}/>}</section>}
      {module==='sales'&&<section className="panel"><div className="panel-heading"><div><h2>Satış siparişleri</h2><p>Faturalanan tutar sipariş kalemlerinden gelir. Sevkiyat ile tahsilat ayrı izlenir.</p></div><span className="pill">{money(saleTotal)}</span></div>{state.sales.length?<div className="table-scroll"><table><thead><tr><th>SİPARİŞ / MÜŞTERİ</th><th>ÜRÜNLER</th><th>TUTAR</th><th>FİNANS / SEVKİYAT</th><th/></tr></thead><tbody>{state.sales.map(s=><tr key={s.id}><td><strong>{s.code}</strong><small>{contactName(s.contactId)}</small></td><td>{s.lines.map(l=><small key={l.productId}>{l.quantity} × {l.name}</small>)}</td><td className="amount-cell">{money(s.total)}</td><td><Pill value={s.status}/><small>{s.delivered?'Sevk edildi':'Sevkiyat bekliyor'}</small></td><td><div className="erp-row-actions">{!['cancelled','refunded'].includes(s.status)&&<Button asChild size="sm" variant="secondary"><a href={s.invoiceId?'/finance?invoice='+s.invoiceId:'/finance?order='+s.id}>{s.invoiceId?'Faturayı aç':'Stellar ile faturala'}<ArrowUpRight size={12}/></a></Button>}{!s.delivered&&!['cancelled','refunded'].includes(s.status)&&<Button size="sm" variant="secondary" disabled={!!busy} onClick={()=>mutate('deliver',{id:s.id})}>Sevk et</Button>}</div></td></tr>)}</tbody></table></div>:<Empty title="Satışın ortak kayıttan başlasın." text="Müşteri, ürün ve miktarları seç. Sipariş toplamı otomatik hesaplansın." icon={<ShoppingCart size={28}/>} action="Satış siparişi oluştur" onClick={()=>setForm({kind:'sales'})}/>}</section>}
      {module==='purchasing'&&<section className="panel"><div className="panel-heading"><div><h2>Satın alma & mal kabulü</h2><p>Mal kabulü stok girişini ve tedarikçi borcunu birlikte kaydeder.</p></div><span className="count-badge">{state.purchases.length}</span></div>{state.purchases.length?<div className="table-scroll"><table><thead><tr><th>SİPARİŞ / TEDARİKÇİ</th><th>ÜRÜNLER</th><th>TUTAR</th><th>DURUM</th><th/></tr></thead><tbody>{state.purchases.map(p=><tr key={p.id}><td><strong>{p.code}</strong><small>{contactName(p.contactId)}</small></td><td>{p.lines.map(l=><small key={l.productId}>{l.quantity} × {l.name}</small>)}</td><td className="amount-cell">{money(p.total)}</td><td><Pill value={p.status}/></td><td>{p.status==='ordered'?<Button size="sm" disabled={!!busy} onClick={()=>mutate('receive',{id:p.id})}>Mal kabulü yap</Button>:<Button asChild variant="secondary" size="sm"><a href={'/finance?payable='+p.payableId}>Ödeme kaydını aç <ArrowUpRight size={12}/></a></Button>}</td></tr>)}</tbody></table></div>:<Empty title="Tedarik sürecini kayda al." text="Tedarikçini ve ürünleri seç. Mal geldiğinde stoğa kabul ederek ödeme yükümlülüğü oluştur." icon={<Truck size={28}/>} action="Satın alma siparişi" onClick={()=>setForm({kind:'purchase'})}/>}</section>}
      {module==='stock'&&<><section className="panel"><div className="panel-heading"><div><h2>Ürünler & mevcut stok</h2><p>Satın alma, üretim ve satış aynı ürün kaydını günceller.</p></div><span className="pill">{lowStock.length} kritik stok</span></div>{state.products.length?<div className="table-scroll"><table><thead><tr><th>ÜRÜN / SKU</th><th>TÜR</th><th>MEVCUT STOK</th><th>SİPARİŞ SEVİYESİ</th><th>BİRİM FİYAT</th></tr></thead><tbody>{state.products.map(p=><tr key={p.id}><td><strong>{p.name}</strong><small>{p.sku}</small></td><td>{p.type==='raw'?'Girdi / hammadde':'Mamul'}</td><td><strong className={p.quantity<=p.reorderPoint?'erp-warning-text':''}>{p.quantity} adet</strong></td><td>{p.reorderPoint} adet</td><td>{money(p.price)}</td></tr>)}</tbody></table></div>:<Empty title="Depodaki her ürünün bir kimliği olsun." text="SKU, ürün türü, açılış stoğu ve birim referans fiyatını kaydet." icon={<Boxes size={28}/>} action="Ürün ekle" onClick={()=>setForm({kind:'product'})}/>}</section><section className="panel erp-secondary-panel"><div className="panel-heading"><div><h2>Stok hareketleri</h2><p>İşlem kaynağı ile birlikte giriş ve çıkışlar.</p></div></div>{state.movements.length?<div className="table-scroll"><table><thead><tr><th>ÜRÜN</th><th>KAYNAK</th><th>MİKTAR</th><th>TARİH</th></tr></thead><tbody>{state.movements.slice(0,30).map(m=><tr key={m.id}><td>{state.products.find(p=>p.id===m.productId)?.name}</td><td>{m.reason}</td><td className={m.quantity>0?'green-text':''}>{m.quantity>0?'+':''}{m.quantity} adet</td><td>{formatDate(m.createdAt)}</td></tr>)}</tbody></table></div>:<Empty title="Stok hareketi henüz yok." text="Açılış, mal kabulü, üretim ve sevkiyat burada izlenir." icon={<Package size={26}/>}/>}</section></>}
      {module==='production'&&<section className="panel"><div className="panel-heading"><div><h2>Üretim iş emirleri</h2><p>Reçete girdileri ile mamul çıktısı tek stok işlemi olarak kaydedilir.</p></div><span className="pill">{waitingProduction.length} planlanan iş</span></div>{state.production.length?<div className="table-scroll"><table><thead><tr><th>İŞ EMRİ / ÇIKTI</th><th>GİRDİ REÇETESİ</th><th>MİKTAR</th><th>DURUM</th><th/></tr></thead><tbody>{state.production.map(j=><tr key={j.id}><td><strong>{j.code}</strong><small>{state.products.find(p=>p.id===j.outputId)?.name}</small></td><td>{j.inputs.map(input=><small key={input.productId}>{input.perUnit*j.quantity} × {state.products.find(p=>p.id===input.productId)?.name}</small>)}</td><td>{j.quantity} adet</td><td><Pill value={j.status}/></td><td>{j.status==='planned'&&<Button size="sm" disabled={!!busy} onClick={()=>mutate('completeProduction',{id:j.id})}>Üretimi tamamla</Button>}</td></tr>)}</tbody></table></div>:<Empty title="Üretim stoğunla birlikte çalışsın." text="Çıktı ürününü, üretim miktarını ve bir ürün için gereken girdileri tanımla." icon={<Factory size={28}/>} action="İş emri oluştur" onClick={()=>setForm({kind:'production'})}/>}</section>}
      {module==='team'&&<><section className="panel"><div className="panel-heading"><div><h2>Çalışanlar</h2><p>Departman, görev ve USDC ödeme planı. Bu prototipte bordro/vergi hesabı yoktur.</p></div><span className="count-badge">{state.employees.length}</span></div>{state.employees.length?<div className="table-scroll"><table><thead><tr><th>ÇALIŞAN</th><th>DEPARTMAN / GÖREV</th><th>AYLIK ÖDEME PLANI</th><th>STELLAR CÜZDANI</th><th/></tr></thead><tbody>{state.employees.map(e=><tr key={e.id}><td><strong>{e.name}</strong></td><td>{e.department}<small>{e.role}</small></td><td>{money(e.salary)}</td><td><code>{e.wallet?shortAddress(e.wallet):'Henüz eklenmedi'}</code></td><td><Button size="sm" variant="secondary" onClick={()=>setForm({kind:'employee',id:e.id})}>Düzenle</Button></td></tr>)}</tbody></table></div>:<Empty title="Ekibinin ortak kaydını oluştur." text="Çalışan kayıtları dönemlik ödeme planını ve Stellar alıcı cüzdanını besler." icon={<Users size={28}/>} action="Çalışan ekle" onClick={()=>setForm({kind:'employee'})}/>}</section><section className="erp-payroll-banner"><div><span className="icon-tile"><Users size={20}/></span><div><strong>Dönemlik çalışan ödemeleri</strong><p>Aynı çalışan için aynı ay ikinci kez ödeme yükümlülüğü oluşturulmaz.</p></div></div><div><input type="month" value={period} onChange={e=>setPeriod(e.target.value)} aria-label="Çalışan ödeme dönemi"/><Button disabled={!!busy||!state.employees.length} onClick={()=>mutate('payroll',{period})}>Ödeme planını oluştur <ArrowRight size={15}/></Button></div></section><section className="panel erp-secondary-panel"><div className="panel-heading"><h2>Çalışan ödeme kayıtları</h2><a className="text-button" href="/finance">Stellar finansı aç <ArrowUpRight size={14}/></a></div>{state.payables.some(p=>p.type==='salary')?<div className="table-scroll"><table><thead><tr><th>ÇALIŞAN / DÖNEM</th><th>TUTAR</th><th>DURUM</th><th/></tr></thead><tbody>{state.payables.filter(p=>p.type==='salary').map(p=><tr key={p.id}><td><strong>{p.recipient}</strong><small>{p.period} · {p.code}</small></td><td>{money(p.amount)}</td><td><Pill value={p.status}/></td><td><Button asChild variant="secondary" size="sm"><a href={'/finance?payable='+p.id}>Ödemeyi aç <ArrowUpRight size={12}/></a></Button></td></tr>)}</tbody></table></div>:<Empty title="Dönemlik ödeme kaydı henüz yok." text="Çalışanlarını ekleyip ödeme dönemi için plan oluştur." icon={<Wallet size={27}/>}/>}</section></>}
      {module==='accounting'&&<><section className="stats-grid three-stats"><Metric name="Açık tedarikçi borçları" value={money(sumAmounts(payables.filter(p=>p.type==='vendor').map(p=>p.amount)))} sub="Mal kabulünden oluşan yükümlülükler" icon={<Truck size={18}/>}/><Metric name="Çalışan ödeme borçları" value={money(sumAmounts(payables.filter(p=>p.type==='salary').map(p=>p.amount)))} sub="Dönemlik ödeme planından oluşur" icon={<Users size={18}/>}/><Metric name="Doğrulanmış tahsilat" value={money(receipts)} sub="Escrow’dan şirkete geçen USDC" icon={<ArrowDownLeft size={18}/>}/></section><section className="panel"><div className="panel-heading"><div><h2>Yönetim muhasebesi defteri</h2><p>Her kayıt eşit tutarda borç/alacak hesabı içerir. Tüm referans tutarlar USDC’dir.</p></div><a className="text-button" href="/finance">Stellar işlemleri <ArrowUpRight size={14}/></a></div>{state.journal.length?<div className="table-scroll"><table><thead><tr><th>KAYNAK / AÇIKLAMA</th><th>BORÇ HESABI</th><th>ALACAK HESABI</th><th>TUTAR</th><th>KANIT</th></tr></thead><tbody>{state.journal.map(j=><tr key={j.id}><td><strong>{j.label}</strong><small>{formatDate(j.createdAt)}</small></td><td>{j.debit}</td><td>{j.credit}</td><td className="amount-cell">{money(j.amount)}</td><td>{j.hash?<a className="hash-link" href={explorer(j.hash)} target="_blank" rel="noreferrer">{shortAddress(j.hash)}<ArrowUpRight size={12}/></a>:<span className="pill">ERP iş kaydı</span>}</td></tr>)}</tbody></table><div className="erp-journal-totals"><span>Toplam borç <b>{money(sumAmounts(state.journal.map(j=>j.amount)))}</b></span><span>Toplam alacak <b>{money(sumAmounts(state.journal.map(j=>j.amount)))}</b></span><span className="green-text"><CheckCheck size={14}/>Dengeli</span></div></div>:<Empty title="Operasyon ve finans aynı defterde." text="Mal kabulü, çalışan ödeme planı ve doğrulanmış Stellar fatura işlemleri kayıt oluşturur." icon={<Landmark size={28}/>}/>}</section><div className="info-strip"><CircleHelp size={18}/><p>Bu defter hackathon için basit yönetim muhasebesi kaydıdır. GİB e-Fatura, vergi, kur farkı, stok maliyetlendirme veya yasal muhasebe entegrasyonu içermez.</p></div></>}
      {module==='settings'&&<div className="connections-grid"><section className="panel erp-settings-panel"><div className="panel-heading"><div><h2>Şirket bilgileri</h2><p>Tüm ERP modülleri bu çalışma alanını paylaşır.</p></div><Building2 size={20} className="muted"/></div><form onSubmit={(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();mutate('company',{name:new FormData(event.currentTarget).get('name')});}}><label>Şirket adı<input key={company?.name} name="name" defaultValue={company?.name} required maxLength={120}/></label><p className="erp-field-help">Bu yerel prototipte şirket çalışma alanı tarayıcının güvenli oturumuyla saklanır. Çok kullanıcılı yetki yönetimi sonraki aşamadır.</p><Button type="submit" disabled={!!busy}>Şirket bilgilerini kaydet</Button></form></section><section className="panel erp-settings-panel"><div className="panel-heading"><div><h2>Şirketin Stellar cüzdanı</h2><p>Ödeme yetkisi Freighter imzasıyla doğrulanır.</p></div><Wallet size={20} className="muted"/></div><div className="erp-settings-wallet">{company?.wallet?<><span className="pill"><span className="network-dot"/>Bağlı · Testnet</span><code>{company.wallet}</code><p>Satış faturaları, tedarikçi ve çalışan ödemeleri bu cüzdana bağlıdır.</p></>:<><strong>Henüz cüzdan eşleştirilmedi.</strong><p>Finans modülünde cüzdanını bağla ve şirket cüzdanı olarak eşleştir.</p></>}{state.connectedAccount&&!company?.wallet?<Button disabled={!!busy} onClick={()=>mutate('linkWallet')}>Bağlı cüzdanı şirketle eşleştir</Button>:<Button asChild variant="secondary"><a href="/finance">Finans hesabını aç </a></Button>}</div></section></div>}
      </>}
      <footer className="main-footer"><span><Link2 size={13}/>Centerp <span className="footer-divider">/</span> İşletme süreçleri & Stellar finansı</span><span>Rise In × Stellar · Genesis 2026 <span className="footer-divider">/</span><span className="network-dot"/>Testnet</span></footer></main></div>
    {notice&&<div className={'toast '+(notice.error?'toast-error':'')} role={notice.error?'alert':'status'}>{notice.error?<CircleHelp size={20}/>:<Check size={20}/>}<span>{notice.text}</span><button aria-label="Bildirimi kapat" onClick={()=>setNotice(null)}><X size={16}/></button></div>}
    {form&&state&&<RecordForm key={form.kind+form.id} kind={form.kind} id={form.id} state={state} busy={!!busy} close={()=>setForm(null)} save={mutate}/>}
  </div>;
}

function RecordForm({kind,id,state,busy,close,save}:{kind:FormKind;id?:string;state:ERPState;busy:boolean;close:()=>void;save:(action:string,params:Record<string,unknown>)=>Promise<void>}){
  const contact=state.contacts.find(c=>c.id===id);
  const employee=state.employees.find(e=>e.id===id);
  const [rows,setRows]=useState([{productId:state.products[0]?.id||'',quantity:1,unitPrice:state.products[0]?.price||'1'}]);
  const [ingredients,setIngredients]=useState([{productId:state.products.find(p=>p.type==='raw')?.id||'',perUnit:1}]);
  const [output,setOutput]=useState(state.products.find(p=>p.type==='finished')?.id||'');
  const [batch,setBatch]=useState(1);
  const [partnerType,setPartnerType]=useState<'customer'|'vendor'>(contact?.type||'customer');
  const isOrder=kind==='sales'||kind==='purchase';
  const partners=state.contacts.filter(c=>c.type===(kind==='purchase'?'vendor':'customer'));
  const prerequisites=isOrder?(!partners.length||!state.products.length):kind==='production'?state.products.length<2:false;
  let preview='0';
  try{preview=rows.reduce((sum,row)=>sum.plus(new Decimal(row.unitPrice||0).mul(row.quantity||0)),new Decimal(0)).toFixed(7);}catch{}
  function submit(event:FormEvent<HTMLFormElement>){
    event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget).entries());
    let payload:Record<string,unknown>={...data,id};
    if(kind==='contact')payload={...payload,type:partnerType};
    if(kind==='product')payload={...payload,quantity:Number(data.quantity),reorderPoint:Number(data.reorderPoint)};
    if(isOrder)payload={contactId:data.contactId,lines:rows};
    if(kind==='production')payload={outputId:output,quantity:batch,inputs:ingredients};
    save(kind,payload);
  }
  return <FormDialog title={formTitles[kind]} onClose={close}><form className="invoice-form erp-record-form" onSubmit={submit}>
    {kind==='contact'&&<><div className="erp-form-tabs"><button type="button" className={partnerType==='customer'?'selected':''} onClick={()=>setPartnerType('customer')}>Müşteri</button><button type="button" className={partnerType==='vendor'?'selected':''} onClick={()=>setPartnerType('vendor')}>Tedarikçi</button></div><label>İş ortağı adı<input name="name" required defaultValue={contact?.name} placeholder="Şirket veya kişi adı" maxLength={120}/></label><label>E-posta<input name="email" type="email" defaultValue={contact?.email} placeholder="iletisim@example.com"/></label><label>Stellar public key <span className="optional">isteğe bağlı</span><input name="wallet" defaultValue={contact?.wallet} placeholder="G…" pattern="G[A-Z2-7]{55}"/><small>Stellar faturası veya USDC ödeme için gerekli. Secret key girilmez.</small></label></>}
    {kind==='product'&&<><div className="form-grid"><label>SKU<input name="sku" required placeholder="PRD-001" maxLength={120}/></label><label>Ürün türü<select name="type"><option value="finished">Mamul / satış ürünü</option><option value="raw">Girdi / hammadde</option></select></label></div><label>Ürün adı<input name="name" required maxLength={120} placeholder="Ürün veya malzeme adı"/></label><div className="form-grid"><label>Açılış stok miktarı<input name="quantity" type="number" min="0" max="100000" step="1" required defaultValue="0"/></label><label>Yeniden sipariş seviyesi<input name="reorderPoint" type="number" min="0" max="100000" step="1" required defaultValue="5"/></label></div><label>Birim referans fiyatı (USDC)<input name="price" type="number" min="0.0000001" max="1000000" step="0.0000001" defaultValue="1" required/></label></>}
    {isOrder&&<>{prerequisites&&<div className="form-callout"><CircleHelp size={17}/><p>Önce {kind==='sales'?'müşteri':'tedarikçi'} ve ürün kayıtlarını ekle.</p></div>}<label>{kind==='sales'?'Müşteri':'Tedarikçi'}<select name="contactId" required defaultValue={partners[0]?.id||''}><option value="" disabled>İş ortağı seç</option>{partners.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><div className="erp-line-heading"><strong>Sipariş kalemleri</strong><span>Birim tutarlar USDC</span></div>{rows.map((row,index)=><div className="erp-line-row" key={index}><label>Ürün<select value={row.productId} required aria-label={'Kalem '+(index+1)+' ürünü'} onChange={e=>{const product=state.products.find(p=>p.id===e.target.value);setRows(rows.map((r,i)=>i===index?{...r,productId:e.target.value,unitPrice:product?.price||'1'}:r));}}><option value="" disabled>Ürün seç</option>{state.products.map(p=><option value={p.id} key={p.id}>{p.sku} · {p.name}</option>)}</select></label><label>Adet<input required type="number" min="1" max="100000" step="1" value={row.quantity} aria-label={'Kalem '+(index+1)+' miktarı'} onChange={e=>setRows(rows.map((r,i)=>i===index?{...r,quantity:Number(e.target.value)}:r))}/></label><label>Birim USDC<input required type="number" min="0.0000001" step="0.0000001" value={row.unitPrice} aria-label={'Kalem '+(index+1)+' birim fiyatı'} onChange={e=>setRows(rows.map((r,i)=>i===index?{...r,unitPrice:e.target.value}:r))}/></label><Button type="button" size="icon" variant="ghost" aria-label={'Kalem '+(index+1)+' sil'} disabled={rows.length===1} onClick={()=>setRows(rows.filter((_,i)=>i!==index))}><X size={15}/></Button></div>)}<Button type="button" variant="secondary" size="sm" disabled={rows.length>=20} onClick={()=>setRows([...rows,{productId:state.products[0]?.id||'',quantity:1,unitPrice:state.products[0]?.price||'1'}])}><Plus size={14}/>Kalem ekle</Button><div className="erp-order-total"><span>Sipariş toplamı</span><strong>{money(preview)}</strong></div><div className="form-callout"><Link2 size={17}/><p>{kind==='sales'?'Bu toplam ve müşteri cüzdanı Stellar faturası oluşturulurken kontrol edilir. Sipariş oluşturmak ödeme yapmaz.':'Mal kabulü yapıldığında stok artar, tedarikçi borcu oluşur. Para transferi ayrıca Stellar finans modülünden imzalanır.'}</p></div></>}
    {kind==='employee'&&<><label>Çalışanın adı<input name="name" required defaultValue={employee?.name} maxLength={120}/></label><div className="form-grid"><label>Departman<input name="department" required defaultValue={employee?.department} placeholder="Operasyon"/></label><label>Görev<input name="role" required defaultValue={employee?.role} placeholder="Üretim sorumlusu"/></label></div><label>Aylık ödeme planı (USDC)<input name="salary" type="number" min="0.0000001" step="0.0000001" required defaultValue={employee?.salary||'2'}/><small>Dönemlik ödeme referansıdır; bordro, vergi veya yan hak hesabı yapılmaz.</small></label><label>Çalışan Stellar public key’i<input name="wallet" defaultValue={employee?.wallet} pattern="G[A-Z2-7]{55}" placeholder="G…"/><small>Ödeme planı için isteğe bağlı; USDC transferi için gerekli.</small></label></>}
    {kind==='production'&&<>{prerequisites&&<div className="form-callout"><CircleHelp size={17}/><p>En az bir girdi ve farklı bir çıktı ürünü ekle.</p></div>}<div className="form-grid"><label>Çıktı ürünü<select value={output} onChange={e=>setOutput(e.target.value)} required><option value="" disabled>Mamul seç</option>{state.products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Üretilecek adet<input type="number" min="1" max="100000" step="1" value={batch} required onChange={e=>setBatch(Number(e.target.value))}/></label></div><div className="erp-line-heading"><strong>Bir ürün için girdi reçetesi</strong><span>Toplam tüketim = miktar × üretim adedi</span></div>{ingredients.map((input,index)=><div className="erp-recipe-row" key={index}><label>Girdi ürünü<select required value={input.productId} aria-label={'Girdi '+(index+1)+' ürünü'} onChange={e=>setIngredients(ingredients.map((row,i)=>i===index?{...row,productId:e.target.value}:row))}><option value="" disabled>Girdi seç</option>{state.products.filter(p=>p.id!==output).map(p=><option key={p.id} value={p.id}>{p.name} · stok {p.quantity}</option>)}</select></label><label>Bir ürün için adet<input type="number" min="1" max="100000" step="1" value={input.perUnit} required aria-label={'Girdi '+(index+1)+' birim miktarı'} onChange={e=>setIngredients(ingredients.map((row,i)=>i===index?{...row,perUnit:Number(e.target.value)}:row))}/></label><Button type="button" variant="ghost" size="icon" aria-label={'Girdi '+(index+1)+' sil'} disabled={ingredients.length===1} onClick={()=>setIngredients(ingredients.filter((_,i)=>i!==index))}><X size={15}/></Button></div>)}<Button type="button" variant="secondary" size="sm" disabled={ingredients.length>=20} onClick={()=>setIngredients([...ingredients,{productId:state.products.find(p=>p.id!==output)?.id||'',perUnit:1}])}><Plus size={14}/>Girdi ekle</Button><div className="form-callout"><Factory size={17}/><p>İş emri planlanırken stok değişmez. Tamamlanırken bütün girdiler kontrol edilir; stok yetersizse hiçbir hareket yapılmaz.</p></div></>}
    <div className="modal-footer"><Button type="button" variant="secondary" onClick={close}>Vazgeç</Button><Button type="submit" disabled={busy||prerequisites}><Check size={16}/>Kaydı oluştur{ id?' / güncelle':''}</Button></div>
  </form></FormDialog>;
}
